== INSTALATION ==

 * see https://github.com/asciidoctor/asciidoctor-reveal.js
 ** gem install asciidoctor tilt thread_safe
 ** gem install slim --version 2.1.0


== HOW TO INSTALL REVEAL.JS FOR DEVELOPMENT ==

* git clone https://github.com/hakimel/reveal.js.git
** it's important to know what version of `reveal.js` the *AsciiDoctor Reveal.js* supports - now (September 2015) it should support version 3.1.0

For theming we need full setup of Reveal.js - for up-to-date details see
https://github.com/hakimel/reveal.js#full-setup

. install node.js `dnf install nodejs`
. install grunt `dnf install nodejs-grunt`
. `cd reveal.js`
. install reveal.js dependencies `npm install`

== REVEAL.JS NEW THEME ==

As starting point visit the
https://github.com/hakimel/reveal.js/blob/master/css/theme/README.md

. create a new `scss` file under `css/theme/source`, possibly by cloning some
of the files from `css/theme/source/`
+
there is several things that a new `scss` theming file has to satisfy

* include `css/theme/template/mixins.scss` like `@import "../template/mixins"`
 * include `css/theme/template/settings.scss` like `@import "../template/settings"`
 * define your own overrides under your newly created `scss` file
+
(you can check `settings.scss` to see which variables are available)
 * include `css/theme/template/theme.css` like `@import "../template/theme"`
. generate the `css` representation from the source with command `grunt css-theme`
** now you can see the generated `css` file under `css/theme`

=== ADJUSTING NEW THEME ===

If you want to change your newly created theme and check the changes on-the-fly then

. change theme in `index.html` by redefine `<link rel="stylesheet" href="css/theme/...css" id="theme">`
. serve presentation and monitor source files changes `grunt serve`
. you can check http://localhost:8080
. now any change in your theme `scss` file will cause the `css` file being rendered
and the presentation `index.html` will be reloaded for you to see the change


== HOW TO GENERATE SLIDES ==

== GOOD TO CHECK ==

. verify the version that the _asciidoctor reveal.js_ supports and by that
define which version of _reveal.js_ itself you will checkout
