= HOWTO WORK WITH ASCIIDOCTOR-REVEAL.JS =

Introduction how to create a slides

== INSTALLATION OF ASCIIDOCTOR-REVEAL.JS ==

 * see https://github.com/asciidoctor/asciidoctor-reveal.js
 ** `dnf install gem` _(as root)_
 ** `gem install asciidoctor tilt thread_safe` _(as user)_
 ** `gem install slim --version 2.1.0` _(as user)_


== INSTALLATION of REVEAL.JS FOR DEVELOPMENT ==

* git clone https://github.com/hakimel/reveal.js.git

[IMPORTANT]
====
It's important to know what version of `reveal.js` the *AsciiDoctor Reveal.js*
supports

 * September 2015: it should support version 3.1.0
 * January 2016: will be trying to run with 3.2.0
====

For theming we need full setup of Reveal.js - for up-to-date details see
https://github.com/hakimel/reveal.js#full-setup

=== These are prerequisities to install once for a machine

. install node.js `dnf install nodejs`
. install grunt `dnf install nodejs-grunt nodejs-grunt-cli`

=== These are prerequisities to install each time when repo is cloned

. going to cloned reveal.js repo `cd reveal.js`
. install reveal.js dependencies `npm install`

== REVEAL.JS NEW THEME ==

As starting point visit the
https://github.com/hakimel/reveal.js/blob/master/css/theme/README.md

. create a new `scss` file under `css/theme/source`, possibly by cloning some
of the files from `css/theme/source/`
+
there is several things that a new `scss` theming file has to satisfy

* include `css/theme/template/mixins.scss` like `@import "../template/mixins"`
 * include `css/theme/template/settings.scss` like `@import "../template/settings"`
 * define your own overrides under your newly created `scss` file
+
(you can check `settings.scss` to see which variables are available)
 * include `css/theme/template/theme.css` like `@import "../template/theme"`
. generate the `css` representation from the source with command `grunt css-themes`
** now you can see the generated `css` file under `css/theme`

=== ADJUSTING NEW THEME ===

If you want to change your newly created theme and check the changes on-the-fly then

. change theme in `index.html` by redefine `<link rel="stylesheet" href="css/theme/...css" id="theme">`
. serve presentation and monitor source files changes `grunt serve`
. you can check http://localhost:8080
. now any change in your theme `scss` file will cause the `css` file being rendered
and the presentation `index.html` will be reloaded for you to see the change


== HOW TO GENERATE SLIDES ==

* `asciidoctor -T asciidoctor-reveal.js/templates/slim slides.adoc`
+
this will generate file `slides.html` (all the links to css and js will point
to a folder `reveal.js` of the current directory)

[NOTE]
====
check `reveal.js` properties

* // Bounds for smallest/largest possible scale to apply to content +
  minScale: 1, +
  maxScale: 1.5,
* zoomKey: \'ctrl',

====

== HOW TO MANAGE SUBMODULES ==

To start work with the repo you will need something like

```
git clone git@github.com:ochaloup/btm-presentation.git
cd btm-presentation
git submodule init
git submodule update
```

Now you can normally work with the submodules or parent project.

Changing submodule data. You need to push the changes to remote repository of the submodule.

```
cd slides/reveal.js
echo "test" >> README.md
git add . && git ci -m "Test change of readme file"
git push origin master
```

When submodule is changed the parent project will talk about change.
This _change_ records update of pointer.

```
cd ..
git add . && git ci -m "Update of reveal.js"
git push origin master
```

If somebody else want to get data of submodule back to the `btm-presentation`
project he needs to run.

Running on parent project (`cd btm-presentation`) - updating to get _pointer_
of the submodule:

* `git pull origin master`

Fetching data from submodule repository to sync data on updated _pointer_
(_pointer_ updated in step before)

* `git submodule update`


== IMAGES ADJUSTMENTS ==

How to use Gimp to enhance quality of scanned black and white image - my points here.
First see https://www.youtube.com/watch?v=1_vEI8Jqtlo as base on that tutorial.

* Selection tool by color - select white color and delete the content of selection (Ctrl+X)
* Filters -> Artistic -> Softglow (example of values: 22; 0.68; 1)
* Filters -> Artistic -> Cartoon (example of values: 50; 0.042)
* Take a bruch and rubber and clean the rest manually
