== Simple byteman instrumentation

. be at `part1/01_simple`
. `cd byteman-simple`
. `mvn install`
. `java -cp target/byteman-simple-1.0-SNAPSHOT.jar org.jboss.qa.App`
. `export BYTEMAN_HOME=/opt/byteman`
. `java -javaagent:$BYTEMAN_HOME/lib/byteman.jar=script:../simple.btm -cp target/byteman-simple-1.0-SNAPSHOT.jar org.jboss.qa.App`

[NOTE]
====
You can get verbose info what byteman does with argument `-Dorg.jboss.byteman.verbose`
and `-Dorg.jboss.byteman.debug=true` to get debug messages from rules.

```
java -javaagent:$BYTEMAN_HOME/lib/byteman.jar=script:../simple.btm -Dorg.jboss.byteman.verbose -cp target/byteman-simple-1.0-SNAPSHOT.jar org.jboss.qa.App
```
====

If you want to change (intercept) core java classes (like `java.lang.String` etc.)
you need to get Byteman being loaded by boot class loader which is defined with
javaagent option `boot:`.

. enable rule _Change message number 2_ and run with `boot` (otherwise you get exception)
. `java -javaagent:$BYTEMAN_HOME/lib/byteman.jar=script:../simple.btm,boot:$BYTEMAN_HOME/lib/byteman.jar -cp target/byteman-simple-1.0-SNAPSHOT.jar org.jboss.qa.App`

or alternativelly something

. `export JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$BYTEMAN_HOME/lib/byteman.jar -javaagent:$BYTEMAN_HOME/lib/byteman.jar=script:../simple.btm`

Exception when boot is not used

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/byteman/rule/exception/EarlyReturnException
  at java.io.PrintStream.println(PrintStream.java)
  at org.jboss.qa.App.main(App.java:12)
```

Other important option to set is `-Dorg.jboss.byteman.transform.all` which enables injection
into `java.lang` classes. Normally the agent ignores rules which apply to this package on the grounds that by modifying these classes it will likely
shoot itself in the foot changing the JVM functionality it relies on to execute rules.
